version: "3.9"    

services:
  auth-service:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
    - CLIENT_ID=${CLIENT_ID}
    - CLIENT_SECRET=${CLIENT_SECRET}
    - TOKEN_URL=${TOKEN_URL}
    - REDIRECT_URL=${REDIRECT_URL}
