version: "3.9"

networks:
  foonet:
  barnet:

services:
  
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3000
    networks:
      - foonet
      - barnet

  user-service:
    build: 
      context: ./user-service
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 3002:3000
    networks:
      - foonet
      - barnet

  # kraken_designer:
  #   image: devopsfaith/krakendesigner:v2.0
  #   ports:
  #     - 8787:80
  #   networks:
  #     - net
  krakend_ce:
    image: devopsfaith/krakend:2
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    depends_on:
      - auth-service
      - user-service
    networks:
      - foonet
      - barnet


