version: "3.9"    
services:
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3000

  user-service:
    build: 
      context: ./user-service
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 3002:3000

  api-gateway:
    image: devopsfaith/krakend:2
    volumes:
      - ./api-gateway:/etc/krakend
    ports:
      - "8080:8080"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    depends_on:
      - auth-service
      - user-service


