version: "3.9"    
name: rubber-duck-tools
services:
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3000
    depends_on:
      - api-gateway

  user-service:
    build: 
      context: ./user-service
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 3002:3000
    depends_on:
      - user-service-db
      - user-service-db-explorer
      - api-gateway

  user-service-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Foobar1!
    ports:
      - 27017:27017

  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
  
  rdt-app:
    build: 
      context: ./clients/rdt-app
      dockerfile: ./Dockerfile
    ports:
      - "4200:80"

